{% set name = "alphalens" %}
{% set version = "0.3.6" %}
{% set sha256 = "5fdd72a8a6845e9e728389a0388734df3815acf6ef04551ecc09040de468f6a2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - ipython >=3.2.3
    - matplotlib >=1.4.0
    - numpy >=1.9.1
    - pandas >=0.18.0
    - scipy >=0.14.0
    - seaborn >=0.6.0
    - statsmodels >=0.6.1

test:
  imports:
    - alphalens
    - alphalens.tests

about:
  home: http://quantopian.github.io/alphalens/
  license: Apache 2.0
  license_family: Apache
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Performance analysis of predictive (alpha) stock factors'

  description: |
    Alphalens is a Python Library for performance analysis of predictive (alpha)
    stock factors. Alphalens works great with the Zipline open source backtesting
    library, and Pyfolio which provides performance and risk analysis of 
    financial portfolios.
  doc_url: http://quantopian.github.io/alphalens/
  dev_url: https://github.com/quantopian/alphalens

extra:
  recipe-maintainers:
    - alen12345
