travis:
  secure:
    BINSTAR_TOKEN: N3h+Na+Uv7WRp6prCeIdK6ysuZNJbYVS5j/VTl9ZfsDbk7GSiH9VldP2SJvREebmhYcCMv7y5wcQPPJuEAg3jJiPPeAp7PoOejxVXbbGXnPc7xQkrvS9LOvfI8xrmKKrge2DWfnGB3SD2f2EeR+cOnFDOf7uX5eoAGDpRgmxqwjsV5qXrgRKl+Hfnh11uRT7ioCLW0iG/b7j0F8rOtAr0NMWIgp2ikm3MYmvDvekHA3qiPFqBblxYA0kSIv5DjBwc4OV9HDWW8nDIW4eNMAgOcOIDNCV3VbaKh037DCWnB+ANxXPilSF138tzh/lR+XzDDybyGn6hfG0JQo8s3YTLK3aFT4/Cyk82Pi222vk4HiIR8lFn+OCPTGB6idpYlO9QF5DkuGZZLmdMGd/WLCFu/ky+9EsgB6PNhDQNnujYKnBv9yYz1m3cuhhKNMK9W3H+dG/TPeI8gm85Nmbbbyqrl4759DwFjkBuTGzcVRL7+5NGMOWv8Y6RZbUF6cDMSaAS7BcJf/8tMihbd57KJUxF9lnkyEaD6I2G2XmeB3KBoeFHSmZgeaMnlBF9Y3IVGLL7TKpKDHqpje0D5VnBzfZhaxPeW/hIPWYKjBu8P+pBI/FWTDYbtfgqAlh7YAYBdyoj/iRuSrSYWm5T0le4YSbDY/dvqyHWuJJkYIq1EvyCc0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
